
name: Create Release

on:

  workflow_run:
    workflows: [Generate tag]
    types:
      - completed

jobs:
  release-after-tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: cd ${{github.workspace}}
      - name: Get latest tag
        id: tagstep
        run: echo "tag=$(git describe --abbrev=0)" >> $GITHUB_OUTPUT  
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          tag_name: ${{steps.tagstep.outputs.tag}}
          body: "Release ${{steps.tagstep.outputs.tag}}"

      