
name: Create Release

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compute-major:
    if: ${{ contains(github.event.head_commit.message, '[MAJOR]') }}
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.compute-tag.outputs.next_tag}}
    steps:
      - id: compute-tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: major
  
  compute-minor:
    if: ${{ contains(github.event.head_commit.message, '[MINOR]') }}
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.compute-tag.outputs.next_tag}}
    steps:
      - id: compute-tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: minor
  
  compute-patch:
    if: ${{ contains(github.event.head_commit.message, '[PATCH]') }}
    runs-on: ubuntu-latest
    outputs: 
      version: ${{steps.compute-tag.outputs.next_tag}}
    steps:
      - id: compute-tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: patch

  release:
    runs-on: ubuntu-latest
    if: ${{contains(github.event.head_commit.message, '[MAJOR]') || contains(github.event.head_commit.message, '[MINOR]') || contains(github.event.head_commit.message, '[PATCH]')}}
    needs: [compute-major, compute-minor, compute-patch]
    steps:
      - name: "print-tag"
        run: echo "Next tag will be ${{needs.*.outputs.version}}"





          