
name: Create Release

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    if: ${{contains(github.event.head_commit.message, '[MAJOR]') || contains(github.event.head_commit.message, '[MINOR]') || contains(github.event.head_commit.message, '[PATCH]')}}
    runs-on: ubuntu-latest
    steps:
      - id: compute-versiontype
        run: echo "versiontype=${{ contains(github.event.head_commit.message, '[MAJOR]') && 'major' || contains(github.event.head_commit.message, '[MINOR]') && 'minor' || contains(github.event.head_commit.message, '[PATCH]') && 'patch'}}" >> "$GITHUB_OUTPUT"

      - name: "Print type"
        run: echo ${{steps.compute-versiontype.outputs.versiontype}}

      - id: compute-tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: ${{steps.compute-versiontype.outputs.versiontype}}

      - name: "print-tag"
        run: echo "Next tag will be  ${{steps.compute-tag.outputs.next_tag}}"
      
      





          