
name: Create Release

on:

  workflow_run:
    workflows: [Generate tag]
    types:
      - completed

  push:
    branches: main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      