
name: Create Release

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-major:
    if: ${{ contains(github.event.head_commit.message, '[MAJOR]') }}
    runs-on: ubuntu-latest
    steps:
      - id: compute_tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: major
      - name: "print-tag"
        run: echo "Next tag will be ${{steps.compute_tag.outputs.next_tag}}"
  
  release-minor:
    if: ${{ contains(github.event.head_commit.message, '[MINOR]') }}
    runs-on: ubuntu-latest
    steps:
      - id: compute_tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: minor
      - name: "print-tag"
        run: echo "Next tag will be ${{steps.compute_tag.outputs.next_tag}}"
  
  release-patch:
    if: ${{ contains(github.event.head_commit.message, '[PATCH]') }}
    runs-on: ubuntu-latest
    steps:
      - id: compute_tag
        uses: craig-day/compute-tag@v15
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: patch
      - name: "print-tag"
        run: echo "Next tag will be ${{steps.compute_tag.outputs.next_tag}}"





          