
name: Create Release

on:
  #By default this workflow is intended to run after a tag is generated based on the commit message
  workflow_run:
    workflows: [Generate tag]
    types:
      - completed
  
  #Tagging manually can be an option to trigger a specific release, do this with extra care!
#  push:
#    tags:
#      - "v*.*.*"
      
jobs:
  build-artifact:
    if: ${{ github.event.workflow_run.conclusion == 'success' ||  github.event_name == 'push'}} 
    runs-on: ubuntu-latest
    steps:
      - run: echo "Doing something..."

  release-after-tag:
    needs: build-artifact
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - run: cd ${{github.workspace}}
      - name: Get latest tag
        id: tagstep
        run: echo "tag=$(git describe --abbrev=0)" >> $GITHUB_OUTPUT  
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with: 
          tag_name: ${{steps.tagstep.outputs.tag}}
          name: "Release ${{steps.tagstep.outputs.tag}}"
  
  release-on-push-tag:
    needs: build-artifact
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 0
      - run: cd ${{github.workspace}}
      - name: Get latest tag
        id: tagstep
        run: echo "tag=$(git describe --abbrev=0)" >> $GITHUB_OUTPUT  
      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with: 
          tag_name: ${{steps.tagstep.outputs.tag}}
          name: "Release ${{steps.tagstep.outputs.tag}}"
          
      