
name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "BRANCH=$branch" >> $GITHUB_ENV
          echo "Branch is $branch."

  release:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.branch == 'main' }} # only run if branch is master

    steps:
      - run: echo "Creating release for repository..."
