
name: Generate Tag

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  workflow_dispatch: 

jobs:
  create-new-tag:
    if: ${{contains(github.event.head_commit.message, '[MAJOR]') || contains(github.event.head_commit.message, '[MINOR]') || contains(github.event.head_commit.message, '[PATCH]')}}
    runs-on: ubuntu-latest
    steps:
      - id: compute-versiontype
        run: echo "versiontype=${{ contains(github.event.head_commit.message, '[MAJOR]') && 'major' || contains(github.event.head_commit.message, '[MINOR]') && 'minor' || contains(github.event.head_commit.message, '[PATCH]') && 'patch'}}" >> "$GITHUB_OUTPUT"

      - id: compute-tag
        uses: craig-day/compute-tag@v16
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: ${{steps.compute-versiontype.outputs.versiontype}}

      - run: echo "Next tag will be  ${{steps.compute-tag.outputs.next_tag}}"
      
      - uses: actions/checkout@v3

      - run: cd ${{github.workspace}}

      - uses: rickstaa/action-create-tag@v1
        id: tag-create
        with:
          tag:  ${{steps.compute-tag.outputs.next_tag}}
          tag_exists_error: false
      - name: Release
        uses: softprops/action-gh-release@v1
      
    




          