
name: Test

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    tags:
        - "v*.*.*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-tag:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{github.ref}}
      - name: Use tag
        run: |
          TAG=${{github.ref}}
          echo `expr match "$TAG" '.*\(*.*.*)'`